version: '4'

services:
  test-meet-me-here-postgres:
    container_name: test-meet-me-here-postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    command: postgres -p ${POSTGRES_PORT}

  test-meet-me-here-api:
    container_name: test-meet-me-here-api
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - test-meet-me-here-postgres
    command: bash -c "npm run test:unit:localhost"
