name: PullRequest
on: [push]
  branches:
    - main
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "123456"
          envkey_POSTGRES_DB: "drivenops_test"
          envkey_DATABASE_URL: "postgres://postgres:123456@db:5432/drivenops_test"
          directory: back-end/
          file_name: .env.test
      - name: Run tests
        run: docker compose --file ./docker-compose.test.yml --env-file ./.env.test up --build --abort-on-container-exit --exit-code-from test-meet-me-here-api
        # run: docker-compose -f docker-compose.test.yml run node_app npm run test
