name: PullRequest
on:
  push:
    branches:
      - main
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "mmh_test"
          envkey_DATABASE_URL: "postgres://postgres:postgres@db:5432/mmh_test"
          directory: ./
          file_name: .env.test
      - name: Run tests
        run: docker compose --file ./docker-compose.test.yml --env-file ./.env.test up --build --abort-on-container-exit --exit-code-from test-meet-me-here-api
        # run: docker-compose -f docker-compose.test.yml run node_app npm run test
